[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.146"
sdl2 = "0.35.2"
parking_lot = "0.12.1"

[lib]
crate-type=["staticlib"]